name: build executables

on:
  push:
    tags:
      - "v*"

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@master
        with: { python-version: 3.9 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        # run: pip install -r requirements.txt
        run: pip install PyInstaller


      - name: build
        run: pyinstaller encoder_for_discord.py --onefile

      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: Encoder_for_Discord-windows
          path: dist/Encoder_for_Discord.exe

  # macOS-build:
  #   runs-on: macOS-latest
  #   steps:
  #     - name: Checkout commit
  #       uses: actions/checkout@master

  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@master
  #       with: { python-version: 3.9 }

  #     - name: Upgrade pip
  #       run: python -m pip install --upgrade pip PyInstaller

  #     - name: Install requirements
  #       run: pip install -r requirements.txt

  #     - name: build
  #       run: pyinstaller -F encoder_for_discord.py

  #     - name: upload
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: Encoder_for_Discord-macos
  #         path: dist/Encoder_for_Discord

  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@master
        with: { python-version: 3.9 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        # run: pip install -r requirements.txt
        run: pip install PyInstaller

      - name: build
        run: pyinstaller -F encoder_for_discord.py

      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: Encoder_for_Discord-linux
          path: dist/encoder_for_discord

  release:
    # needs: [ubuntu-build, macOS-build, windows-build]
    # runs-on: ubuntu-latest
    needs: [ubuntu-build, windows-build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux
        uses: actions/download-artifact@v1
        with:
          name: Encoder_for_Discord-linux

      # - name: Download Mac
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: Encoder_for_Discord-macos

      - name: Download Windows
        uses: actions/download-artifact@v1
        with:
          name: Encoder_for_Discord-windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Zip
        # run: |
        #   tar -C Encoder_for_Discord-macos -pczvf Encoder_for_Discord-macos.tar.gz Encoder_for_Discord
        #   tar -C Encoder_for_Discord-linux -pczvf Encoder_for_Discord-linux.tar.gz Encoder_for_Discord
        #   zip --junk-paths Encoder_for_Discord-windows ./Encoder_for_Discord-windows/Encoder_for_Discord.exe
        run: |
          tar -C Encoder_for_Discord-linux -pczvf Encoder_for_Discord-${{ steps.tag.outputs.version }}-linux.tar.gz encoder_for_discord
          zip --junk-paths Encoder_for_Discord-${{ steps.tag.outputs.version }}-windows ./Encoder_for_Discord-windows/Encoder_for_Discord.exe
        # run: zip --junk-paths Encoder_for_Discord-windows ./Encoder_for_Discord-windows/Encoder_for_Discord.exe
      # - name: Append Binary
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./Encoder_for_Discord-macos.tar.gz
      #     asset_name: Encoder_for_Discord-macos.tar.gz
      #     asset_content_type: application/gzip

      - name: Append Binary - linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Encoder_for_Discord-${{ steps.tag.outputs.version }}-linux.tar.gz
          asset_name: Encoder_for_Discord-${{ steps.tag.outputs.version }}-linux.tar.gz
          asset_content_type: application/gzip

      - name: Append Binary - windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Encoder_for_Discord-${{ steps.tag.outputs.version }}-windows.zip
          asset_name: Encoder_for_Discord-${{ steps.tag.outputs.version }}-windows.zip
          asset_content_type: application/zip
